app = "n8n-fly" # wird bei "fly launch" automatisch ersetzt

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  GENERIC_TIMEZONE = "Europe/Berlin"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "dein_passwort"

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[experimental]
  auto_rollback = true
